# Generated by Django 4.0.3 on 2022-04-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardpaul', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(max_length=100),
        ),
    ]
