# Generated by Django 4.0.3 on 2022-04-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awardpaul', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='poster',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
