# Generated by Django 4.0.3 on 2022-04-10 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awardpaul', '0007_project_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='poster',
        ),
    ]
